# Generated by Django 4.2.9 on 2025-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile_agent_status_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
