# Generated by Django 4.2.9 on 2025-10-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_placedorder_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='agent_name',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='agent_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='agents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'agent'}, related_name='assigned_orders', to='home.userprofile'),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
